#!/usr/bin/env bash
# tools/tasktool/install.sh — install/update the ~/.local/bin/tasktool shim.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"   # → tools/
TARGET="${HOME}/.local/bin/tasktool"
FORCE="${1:-}"

EXPECTED_SHIM="#!/usr/bin/env bash
# tasktool shim — generated by tasktool/install.sh
exec python3 -m tasktool \"\$@\""

mkdir -p "$(dirname "$TARGET")"

if [[ -f "$TARGET" ]] && [[ "$FORCE" != "--force" ]]; then
  current="$(cat "$TARGET")"
  if [[ "$current" == "$EXPECTED_SHIM" ]] || grep -q "tasktool shim" "$TARGET" 2>/dev/null; then
    echo "tasktool shim already installed (matches). Updating PYTHONPATH note..."
  else
    echo "ERROR: $TARGET exists and is not a tasktool shim. Re-run with --force to overwrite." >&2
    exit 1
  fi
fi

cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# tasktool shim — generated by tasktool/install.sh
export PYTHONPATH="${PKG_ROOT}\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m tasktool "\$@"
EOF
chmod +x "$TARGET"

echo "Installed $TARGET"
echo "Pointing at $PKG_ROOT/tasktool"
"$TARGET" --help >/dev/null
echo "Self-test passed."
