#!/usr/bin/env bash
# tools/tasktool/install.sh — install/update the ~/.local/bin/tasktool shim.
set -euo pipefail

# --- hook installer (must precede shim-install logic) ---------------------
if [[ "${1:-}" == "--hook" ]]; then
  shift
  FORCE_HOOK=0
  if [[ "${1:-}" == "--force" ]]; then FORCE_HOOK=1; shift; fi
  REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  if [[ -z "$REPO_ROOT" ]]; then
    echo "install.sh --hook: must be run inside a git working tree" >&2
    exit 1
  fi
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  SOURCE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"   # → superstar repo root
  HOOK_SRC="$SCRIPT_DIR/templates/pre-commit-tasktool"
  HOOK_DEST="$REPO_ROOT/.git/hooks/pre-commit"
  if [[ -f "$HOOK_DEST" && "$FORCE_HOOK" -ne 1 ]]; then
    if grep -q 'tasktool-pre-commit-hook' "$HOOK_DEST" 2>/dev/null \
       || grep -q 'superstar-hook-name: tasktool-pre-commit' "$HOOK_DEST" 2>/dev/null; then
      : # ours; rewrite below
    else
      echo "install.sh --hook: $HOOK_DEST exists and is not a tasktool hook. Re-run with --force to overwrite." >&2
      exit 1
    fi
  fi
  SRC_VERSION="$(head -n1 "$SOURCE_ROOT/VERSION" | tr -d '[:space:]')"
  if [[ -z "$SRC_VERSION" ]]; then
    echo "install.sh --hook: $SOURCE_ROOT/VERSION is missing or empty" >&2
    exit 1
  fi
  GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if [[ "$SOURCE_ROOT" == "$HOME/"* ]]; then
    STAMP_SOURCE_ROOT="\$HOME/${SOURCE_ROOT#"$HOME/"}"
  else
    STAMP_SOURCE_ROOT="$SOURCE_ROOT"
  fi
  TMP="$(mktemp)"
  sed \
    -e "s|__SUPERSTAR_HOOK_VERSION__|$SRC_VERSION|" \
    -e "s|__SUPERSTAR_HOOK_SOURCE_ROOT__|${STAMP_SOURCE_ROOT//|/\\|}|" \
    -e "s|__SUPERSTAR_HOOK_GENERATED_AT__|$GENERATED_AT|" \
    "$HOOK_SRC" > "$TMP"
  install -m 0755 "$TMP" "$HOOK_DEST"
  rm -f "$TMP"
  echo "Installed $HOOK_DEST"
  exit 0
fi
# --------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"   # → tools/
SOURCE_ROOT="$(cd "$PKG_ROOT/.." && pwd)"  # → repo root
TARGET="${HOME}/.local/bin/tasktool"
FORCE="${1:-}"

FRAGMENT="$SOURCE_ROOT/scripts/lib/shim-version-check.sh"
if [[ ! -r "$FRAGMENT" ]]; then
  echo "ERROR: shim-version-check fragment missing: $FRAGMENT" >&2
  exit 1
fi
SRC_VERSION="$(head -n1 "$SOURCE_ROOT/VERSION" | tr -d '[:space:]')"
if [[ -z "$SRC_VERSION" ]]; then
  echo "ERROR: $SOURCE_ROOT/VERSION is missing or empty" >&2
  exit 1
fi
GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

if [[ "$PKG_ROOT" == "$HOME/"* ]]; then
  STAMP_SOURCE_ROOT="\$HOME/${SOURCE_ROOT#"$HOME/"}"
  PKG_EXPR="\$HOME/${PKG_ROOT#"$HOME/"}"
else
  STAMP_SOURCE_ROOT="$SOURCE_ROOT"
  PKG_EXPR="$PKG_ROOT"
fi

mkdir -p "$(dirname "$TARGET")"

if [[ -f "$TARGET" ]] && [[ "$FORCE" != "--force" ]]; then
  if grep -q "tasktool shim" "$TARGET" 2>/dev/null || grep -q "superstar-shim-name: tasktool" "$TARGET" 2>/dev/null; then
    : # ours; rewrite below
  else
    echo "ERROR: $TARGET exists and is not a tasktool shim. Re-run with --force to overwrite." >&2
    exit 1
  fi
fi

{
  cat <<EOF
#!/usr/bin/env bash
# tasktool shim — generated by tasktool/install.sh
# superstar-shim
# superstar-shim-name: tasktool
# superstar-shim-version: $SRC_VERSION
# superstar-shim-source-root: $STAMP_SOURCE_ROOT
# superstar-shim-installer: tools/tasktool/install.sh
# superstar-shim-generated-at: $GENERATED_AT

EOF
  cat "$FRAGMENT"
  cat <<EOF

__superstar_check_version "$SRC_VERSION" \\
    "tasktool" \\
    "$STAMP_SOURCE_ROOT" \\
    "tools/tasktool/install.sh"

export PYTHONPATH="$PKG_EXPR\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m tasktool "\$@"
EOF
} > "$TARGET"

chmod +x "$TARGET"

echo "Installed $TARGET"
echo "Pointing at $PKG_ROOT/tasktool"
"$TARGET" --help >/dev/null
echo "Self-test passed."
