#!/usr/bin/env bash
# skills/external-review/install.sh - install/update the external-reviewer shim.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SOURCE_ROOT="${EXTERNAL_REVIEWER_SOURCE_ROOT:-}"
if [[ -z "$SOURCE_ROOT" ]]; then
  SOURCE_ROOT="$PLUGIN_ROOT"
  case "$PLUGIN_ROOT" in
    */plugins/cache/*/*/*)
      STABLE_ROOT="$(dirname "$PLUGIN_ROOT")/current"
      if [[ -f "$STABLE_ROOT/skills/external-review/scripts/external-reviewer.py" ]]; then
        SOURCE_ROOT="$STABLE_ROOT"
      fi
      ;;
  esac
fi
SOURCE_SCRIPT="$SOURCE_ROOT/skills/external-review/scripts/external-reviewer.py"
TARGET_DIR="${EXTERNAL_REVIEWER_BIN:-${HOME}/.local/bin}"
TARGET="$TARGET_DIR/external-reviewer"
FORCE="${1:-}"

if [[ ! -f "$SOURCE_SCRIPT" ]]; then
  echo "ERROR: source bridge not found: $SOURCE_SCRIPT" >&2
  exit 1
fi

mkdir -p "$TARGET_DIR"

if [[ -f "$TARGET" && "$FORCE" != "--force" ]]; then
  if grep -q "external-reviewer shim" "$TARGET" 2>/dev/null; then
    echo "external-reviewer shim already installed. Updating source path..."
    # Intentionally fall through and rewrite the shim with the current source path.
  else
    echo "ERROR: $TARGET exists and is not an external-reviewer shim. Re-run with --force to overwrite." >&2
    exit 1
  fi
fi

if [[ "$SOURCE_SCRIPT" == "$HOME/"* ]]; then
  SOURCE_EXPR="\$HOME/${SOURCE_SCRIPT#"$HOME/"}"
else
  SOURCE_EXPR="$SOURCE_SCRIPT"
fi

cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# external-reviewer shim - generated by Superstar skills/external-review/install.sh
exec python3 "$SOURCE_EXPR" "\$@"
EOF
chmod +x "$TARGET"

echo "Installed $TARGET"
echo "Pointing at $SOURCE_SCRIPT"
"$TARGET" --help >/dev/null
echo "Self-test passed."
