#!/usr/bin/env bash
# skills/project-setup/install-reviewer-agent.sh
# Generate a thin redirect shim at $EXTERNAL_REVIEWER_BIN/reviewer-agent that
# execs the bash source at $SOURCE_ROOT/skills/project-setup/scripts/reviewer-agent.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SOURCE_ROOT="${EXTERNAL_REVIEWER_SOURCE_ROOT:-}"
if [[ -z "$SOURCE_ROOT" ]]; then
  SOURCE_ROOT="$PLUGIN_ROOT"
  case "$PLUGIN_ROOT" in
    */plugins/cache/*/*/*)
      STABLE_ROOT="$(dirname "$PLUGIN_ROOT")/current"
      if [[ -f "$STABLE_ROOT/skills/project-setup/scripts/reviewer-agent" ]]; then
        SOURCE_ROOT="$STABLE_ROOT"
      fi
      ;;
  esac
fi
SOURCE_SCRIPT="$SOURCE_ROOT/skills/project-setup/scripts/reviewer-agent"
TARGET_DIR="${EXTERNAL_REVIEWER_BIN:-${HOME}/.local/bin}"
TARGET="$TARGET_DIR/reviewer-agent"
FORCE="${1:-}"

if [[ ! -x "$SOURCE_SCRIPT" ]]; then
  echo "ERROR: source wrapper not found or not executable: $SOURCE_SCRIPT" >&2
  exit 1
fi

FRAGMENT="$SOURCE_ROOT/scripts/lib/shim-version-check.sh"
if [[ ! -r "$FRAGMENT" ]]; then
  echo "ERROR: shim-version-check fragment missing: $FRAGMENT" >&2
  exit 1
fi
SRC_VERSION="$(head -n1 "$SOURCE_ROOT/VERSION" | tr -d '[:space:]')"
if [[ -z "$SRC_VERSION" ]]; then
  echo "ERROR: $SOURCE_ROOT/VERSION is missing or empty" >&2
  exit 1
fi
GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

mkdir -p "$TARGET_DIR"

if [[ -f "$TARGET" && "$FORCE" != "--force" ]]; then
  if ! grep -q "superstar-shim-name: reviewer-agent" "$TARGET" 2>/dev/null; then
    echo "ERROR: $TARGET exists and is not a reviewer-agent shim. Re-run with --force to overwrite." >&2
    exit 1
  fi
fi

if [[ "$SOURCE_SCRIPT" == "$HOME/"* ]]; then
  SOURCE_EXPR="\$HOME/${SOURCE_SCRIPT#"$HOME/"}"
  STAMP_SOURCE_ROOT="\$HOME/${SOURCE_ROOT#"$HOME/"}"
else
  SOURCE_EXPR="$SOURCE_SCRIPT"
  STAMP_SOURCE_ROOT="$SOURCE_ROOT"
fi

{
  cat <<EOF
#!/usr/bin/env bash
# reviewer-agent shim - generated by Superstar skills/project-setup/install-reviewer-agent.sh
# superstar-shim
# superstar-shim-name: reviewer-agent
# superstar-shim-version: $SRC_VERSION
# superstar-shim-source-root: $STAMP_SOURCE_ROOT
# superstar-shim-installer: skills/project-setup/install-reviewer-agent.sh
# superstar-shim-generated-at: $GENERATED_AT

EOF
  cat "$FRAGMENT"
  cat <<EOF

__superstar_check_version "$SRC_VERSION" \\
    "reviewer-agent" \\
    "$STAMP_SOURCE_ROOT" \\
    "skills/project-setup/install-reviewer-agent.sh"

exec bash "$SOURCE_EXPR" "\$@"
EOF
} > "$TARGET"

chmod +x "$TARGET"

bash -n "$TARGET"

echo "Installed $TARGET"
echo "Pointing at $SOURCE_SCRIPT"
echo "Self-test passed (bash -n)."
